export const rowData = [
  {
    id: "1",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "2",
    name: "Student2",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "3",
    name: "Student3",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "4",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "5",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "6",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "7",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "8",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "9",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "10",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "11",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "12",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "13",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "14",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
  {
    id: "15",
    name: "Student1",
    year: "1",
    dept: "eee",
    fees: "paid",
    address: "chennai",
  },
];
